### PR TITLE
Fix: Derive original children after trickle config 

### LINKED ISSUE #190: Trickle issue with reset assessment
### Subject of the issue
Trickle adds its models after the assessment is initialised, therefore when an assessment restores its original block models upon resetting, it can exclude a laterly configured trickle button.

Trickle models are injected into blocks and articles at `adapt:start`, from https://github.com/adaptlearning/adapt-contrib-trickle/pull/197 
https://github.com/adaptlearning/adapt-contrib-trickle/blob/82a1c23f24f6508d6ed8c0a65e23ddb11ae9d8ad/js/controller.js#L29-L40

Assessment keeps its article's original children at the model `init` processes, before trickle has added its children.
https://github.com/adaptlearning/adapt-contrib-assessment/blob/e96a10440bc41afcd503d40726154670ed720936/js/adapt-assessmentArticleModel.js#L81
Assessment then restores its article's original children when it is reset, removing any subsequently added trickle button.
https://github.com/adaptlearning/adapt-contrib-assessment/blob/e96a10440bc41afcd503d40726154670ed720936/js/adapt-assessmentArticleModel.js#L157

### PR DESCRIPTION
**Pull request by oliverfoster**
fixes #190

### Fix
* Capture children after spoor has restored and after trickle has added its buttons. This allows assessment to correctly and transparently manage its trickle configuration on reset.

### Replaces
* https://github.com/adaptlearning/adapt-contrib-assessment/pull/188
* https://github.com/adaptlearning/adapt-contrib-trickle/pull/206

### CODE REVIEW

**Review by cahirodoherty-learningpool — APPROVED** [review]
👀

**Review by joe-allen-89 — APPROVED** [review]
👍

**Comment by marissa-champions** [comment]
This fixed the issue for me! Thanks!

**Review by marissa-champions — APPROVED** [review]
This fixed it for me! Thanks

**Pull request merged**
