### PR TITLE
Assessment ID on articles is no longer required

### PR DESCRIPTION
**Pull request by brian-learningpool**
Not all articles will be part of an assessment.

### CODE REVIEW

**Comment by brian-learningpool** [comment]
Partially resolves https://github.com/adaptlearning/adapt_framework/issues/1192.

**Comment by taylortom** [comment]
Works for me!

I guess the only issue with this is that it may cause confusion if it's not been specified but needs to be, as the course likely won't load after preview (or will break when navigating to the article).

Is there a way to add a custom validator which checks for assessment being enabled and makes sure there's an ID?

**Comment by brian-learningpool** [comment]
It doesn't actually cause the course to error if the Assessment ID is left blank but but Enabled is set to `true`.   The code appears to handle that fine.

Unfortunately we don't have support right now for conditional validators.

**Comment by tomgreenfield** [comment]
+1, with a README version bump if being released

**Comment by brian-learningpool** [comment]
Thanks @tomgreenfield -- I missed that.

**Comment by taylortom** [comment]
+1

**Comment by lc-thomasberger** [comment]
+1

**Comment by dancgray** [comment]
+1 would be good to get this released once conflicts resolved

**Pull request merged**
