### PR TITLE
Fix: Include check for model.get('_type') !== 'block' when filtering models (fixes #197)

### LINKED ISSUE #197: Trickle button not showing when assessment has been completed
### Subject of the issue/enhancement/features
With a recent change to filter out globally removed models (https://github.com/adaptlearning/adapt-contrib-assessment/pull/196) the trickle button is now not showing when an assessment has been completed. 

### Your environment
* FW latest
* Firefox/Chrome

### Steps to reproduce
Create assessment article with a trickle button at the end and another article with the results, complete the assessment. 

### Expected behaviour
Trickle button should become visible

### Actual behaviour
No trickle button, user gets stuck

### PR DESCRIPTION
**Pull request by joe-allen-89**
[//]: # (Please title your PR according to eslint commit conventions)
[//]: # (See https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-eslint#eslint-convention for details)

[//]: # (Link the PR to the original issue)
#197 

[//]: # (Delete Fix, Update, New and/or Breaking sections as appropriate)
### Fix
* Include check for model.get('_type') !== 'block' when filtering models (fixes #197)

### CODE REVIEW

**Review by danielghost — COMMENTED** [review]
Seems to only be an issue when trickle `"_onChildren": false` for the article, as that is when the `trickle-button` is included in `this._originalChildModelsStore` and then subsequently removed in the filter.

This works, but is `model.get('_type') !== 'block'` the clearest way to maintain the `trickle-button` in the list? Should it be more explicit regarding the intention, e.g. `model.get('_component') === 'trickle-button'` or `model.get('_isTrackable') == false`. Maybe a comment would suffice?

**Comment by oliverfoster** [comment]
Why is it failing the `data.hasId()` check? The trickle button should be in the data collection still...

Perhaps I never added them to data? https://github.com/adaptlearning/adapt-contrib-trickle/blob/2c550355f0e98f0d50d07f8fdf9614ccfc94ac6d/js/models.js#L294-L319 Weird.

Could you try with a `data.add(trickleButtonModel);` [here](https://github.com/adaptlearning/adapt-contrib-trickle/blob/2c550355f0e98f0d50d07f8fdf9614ccfc94ac6d/js/models.js#L317-L318) as an alternative please? @joe-allen-89

**Comment by joe-allen-89** [comment]
@danielghost - I used model.get('_type') !== 'block' as it's the same method used further down to identify trickle, but yes a comment to make more obvious would have helped. 

@oliverfoster - Tbh I assumed there was a reason you'd kept it out the data, adding the trickle to data also works, I'll close this PR, transfer issue and raise a new PR on trickle if that's your preferred option.

**Comment by oliverfoster** [comment]
I suspect I was probably just cautious about it initially, but there's really no reason not to.

Branching clears cloned models up if it comes to remove them https://github.com/adaptlearning/adapt-contrib-branching/blob/036b75fef296c5e09446ef09dfa3969f29eb695e/js/BranchingSet.js#L313

**Comment by joe-allen-89** [comment]
Closing PR as transferring issue to trickle for alternative fix.

**Comment by joe-allen-89** [comment]
Alternative fix implemented, PR raised - https://github.com/adaptlearning/adapt-contrib-trickle/pull/222

**Pull request closed without merging**
