### PR TITLE
Version 2 Upgrade

### PR DESCRIPTION
**Pull request by zenduo**

### CODE REVIEW

**Comment by moloko** [comment]
package.json version needs changing too

**Comment by zenduo** [comment]
Hi @moloko, @oliverfoster had already given this one 2.0.0 version number, if you check the package.json its already in there. Only thing added here was the framework version.

**Comment by oliverfoster** [comment]
+1

**Comment by hrajotia** [comment]
+1

**Comment by dancgray** [comment]
+1

**Pull request merged**
