### PR TITLE
Amend so a single assessment overrides the _assessment model with val…

### PR DESCRIPTION
**Pull request by danielghost**
…ues from the assessment article, rather than just using the defaults already set in getConfig.

### CODE REVIEW

**Comment by oliverfoster** [comment]
Was the original bug that if the config was set in course.json and you had a single article assessment that it wouldn't pull the single assessment config through?

**Comment by oliverfoster** [comment]
I think this fix probably works more because the if statement is gone rather than redoing the extend. The defaults are a defensive measure against missing them from the config?

**Comment by oliverfoster** [comment]
+1

**Comment by moloko** [comment]
+1

**Comment by hrajotia** [comment]
+1

**Pull request merged**
