### PR TITLE
Restore state fix

### PR DESCRIPTION
**Pull request by chris-steele**

### CODE REVIEW

**Comment by chris-steele** [comment]
Added fix for a bug when returning to an assessment in progress in a new session when using randomisation or question banks - previously all questions would be shown instead of being filtered.

**Comment by moloko** [comment]
+1

**Comment by chris-steele** [comment]
Fixed bug which occurs if:

1. assessment is completed and no more attempts remain (_shouldStoreResponses is disabled)
2. user returns to assessment in new session (assessment will be reset, see specifically _checkIfQuestionsWereRestored)
3. user does not complete assessment and closes course
4. user returns to assessment in new session
5. assessment is not reset and ends up in corrupt state

**Comment by oliverfoster** [comment]
+1

**Comment by moloko** [comment]
+1

**Comment by hrajotia** [comment]
+1

**Pull request merged**
