### PR TITLE
Changes to properties.schema

### PR DESCRIPTION
**Pull request by dancgray**
Includes _canShowMarking. Also see https://github.com/adaptlearning/adapt-contrib-assessment/issues/47

### CODE REVIEW

**Comment by dancgray** [comment]
Fixes https://github.com/adaptlearning/adapt-contrib-assessment/issues/38

**Comment by oliverfoster** [comment]
+1 read but untested

**Comment by brian-learningpool** [comment]
+1, likewise

**Comment by moloko** [comment]
+1

**Pull request merged**
