### PR TITLE
Fix: Bank blocks only, restore other children (fixes #192)

### LINKED ISSUE #192: Assessment Banks with Trickle Not Unlocking Next Article
### Subject of the issue/enhancement/features
Assessment with banks and trickle enabled does not unlock next section after assessment completion.

### Your environment
* framework 5.34.0/trickle 7.1.1/assessment 5.1.10/vanilla
* chrome
* macOS

### Steps to reproduce
Create a course with an assessment and banks and trickle enabled. 
Create an article below it. 
Complete assessment. 
Next article does not unlock.
Returning to menu and then returning to the page does show trickled content however.

### Expected behaviour
The second article should untrickle and unlock after the assessment is completed.

### Actual behaviour
The article does not unlock.

### Screenshots (if you can)
chrome-capture-2024-2-27

### PR DESCRIPTION
**Pull request by oliverfoster**
fixes #192 

### Fix
* Reattached any non-block children, such as trickle buttons, if they are removed in randomisation or banking
* Changed bad variable `_quizBankId` to correct `_quizBankID`

### CODE REVIEW

**Review by marissa-champions — APPROVED** [review]
👍

**Review by marissa-champions — APPROVED** [review]
👍

**Review by marissa-champions — APPROVED** [review]

**Review by cahirodoherty-learningpool — APPROVED** [review]
👀

**Review by joe-allen-89 — APPROVED** [review]
👍

**Pull request merged**
