### PR TITLE
New: Reset and show only incorrect questions

### LINKED ISSUE #184: Reset and show only failed questions
### Subject of the issue
Reset and show only failed questions

### PR DESCRIPTION
**Pull request by oliverfoster**
fixes #184 

### Fix
* Reset and show only incorrect questions

### Notes
* The pass mark is relative to the questions in the attempt only

### CODE REVIEW

**Review by ethan-lp — APPROVED** [review]

**Review by simondate — APPROVED** [review]
Working correctly.

I'm just curious why you designed it this way. I would have imagined this feature would have been implemented in a way where the correctly answered remain but are shown as already answered correctly.

It feels a bit odd to have the new pass mark be calculated without having the original correctly answered questions included.

**Comment by oliverfoster** [comment]
@simondate fair point.

It was only a draft idea at the time of creation. No real design thinking involved. You're more than welcome to update it to accommodate if you like?

I'm not entirely sure how you'd do it, I'd think you'd probably want the correctly answered questions at the top of the assessment and the incorrectly unanswered ones at the bottom? Thinking about trickle and Question Title Numbering you might have some interesting use-cases to consider.

These lines could easily become a sort rather than a removal https://github.com/adaptlearning/adapt-contrib-assessment/pull/185/files#diff-68807b2fce6e8390935769013dfb667988bb81f392cac911ba435b21e5d77149R522-R526

**Review by cahirodoherty-learningpool — APPROVED** [review]
👀

**Comment by simondate** [comment]
> @simondate fair point.
> 
> It was only a draft idea at the time of creation. No real design thinking involved. You're more than welcome to update it to accommodate if you like?
> 
> I'm not entirely sure how you'd do it, I'd think you'd probably want the correctly answered questions at the top of the assessment and the incorrectly unanswered ones at the bottom? Thinking about trickle and Question Title Numbering you might have some interesting use-cases to consider.
> 
> These lines could easily become a sort rather than a removal https://github.com/adaptlearning/adapt-contrib-assessment/pull/185/files#diff-68807b2fce6e8390935769013dfb667988bb81f392cac911ba435b21e5d77149R522-R526

I'm sure there would be other edge cases too like question banks, although come to think of it they would have affected the current PR too.

I'm happy to leave this as is to get it merged.

**Pull request merged**
